### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by mar1n3r0** [BertrandDekoninck/NesedahRik#2]
I am just starting with WindowMaker, the reason which brought me here is that I really like the UI of the discontinued Etoile OS. Can you please give any advice how to install the theme and also to set up the global menu and to move the dock to the left with the transparency effect. Basically how to reproduce the screenshot included in this theme.

Many thanks!

**Comment by BertrandDekoninck** [comment]
You're talking about WindowMaker. NesedahRik is a GNUstep theme and will only be applied to GNUstep apps. If you want a WindowMaker theme, see for instance https://github.com/BertrandDekoninck/WindowMaker-session/tree/master/Windowmaker%20theme.
About NesedahRik : you can copy NesadahRik.theme to ~/GNUstep/Library/Themes (no need to compile it).
Then you can either use SystemPreferences.app to apply it to all GNUstep apps or you can type in a terminal : 
`defaults write NSGlobalDomain GSTheme NesedahRik`

For a global macmenu : 
'defaults write NSGlobalDomain NSInterfaceStyleDefault NSMacintoshInterfaceStyle`

You can set the dock to the left in GWorkspace using its "Desktop" preference (see the "General" tab). If you want transparency, choose "Modern" style. 

And you will find additional scripts and tweaks here : https://github.com/BertrandDekoninck/WindowMaker-session.

And you will find appwrappers for some non-GNUstep  apps (mandatory to be able to launch non GNUstep apps in GWorkspace) there : https://github.com/BertrandDekoninck/RikIcons/tree/master/AppWrappers
